### ISSUE TITLE
Add libpython2.7 to the requirements list

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-docs#107]
Acording to https://forum.seafile-server.org/t/solved-after-upgrade-to-4-2-2-seahub-doesnt-start-any-longer/2030/15?u=shoeper we should add `libpython2.7` to the requirements list at http://manual.seafile.com/deploy/using_mysql.html (seems to be needed with Debian Jessie).

**Comment by freeplant** [comment]
Added
