### ISSUE TITLE
Document to be updated for deploying seahub on non root domain with apache

### ISSUE THREAD

**Issue by kb3dow** [haiwen/seafile-docs#168]
This is wrt issue 1186. 
https://github.com/haiwen/seafile/issues/1186

The man page doc needs to be reflected to say 
ProxyPass "/seafile" "fcgi://127.0.0.1:8000/seafile"

instead of 
ProxyPass "/seafile" "fcgi://127.0.0.1:8000/"

**Comment by shoeper** [comment]
PR = pull request != ticket

**Comment by kb3dow** [comment]
OK, got it. Shall do!

**Comment by darkcircle** [comment]
This issue is already resolved by below commit,

**Comment by shoeper** [comment]
@freeplant close, please.

**Comment by kb3dow** [comment]
Doc fixed.
