### ISSUE TITLE
Suggestion: centralize seafile-docs repository into here one

### ISSUE THREAD

**Issue by darkcircle** [haiwen/seafile-docs#178]
There are three repository for the seafile-docs 

https://github.com/haiwen/seafile-docs (English - original) en
https://github.com/haiwen/seafile-docs-cn (Chinese) zh_CN
https://github.com/haiwen/seafile-docs-ko (Korean, but it doesn't started to translate) ko

We are maintaining documentation separately, and this way is hard to make a new translation and hard to keep translation updated in any time. If original is changed, another one can be hard to update, because, translator cannot find easily what original message is changed. this way doesn't prevent translator working more harder and harder, because there are duplicated message across the line or file by from 2 to about 4 times. in other words, It's very inefficient.

I'm working for introducing po-format generation from markdown and compilation from po to markdown(and wiki?), to make easy to translate, maintain and integrate into the one documentation repository. I'm writing a script by using python3, which will be adopted to the many GNU/Linux distribution, and testing entire steps. If i almost completed i will push my work into my specific repository(forked from here repository).

simple concept is,

1. Maintainer generate po template(*.pot) per directory into the po/ directory (Maintainer can add locale code into the po/LINGUAS file, to make/prevent to generate translation).
2. Translator can translate by importing pot by po editor
3. and then, Translator can request their 'git pull' from the github.
4. Maintainer can compile po created by translator, to make translated markdown document to each language translated, by running simple script.
5. Then, we can see translated documentation from locale/cn, locale/de, locale/ko ... and so on.

**NOTE**: We can replace step 2, 3 by Transifex.

I don't know how to deploy each translated documents into the separated site, but I just able to make an automator for some of steps.

**Comment by shoeper** [comment]
According to my knowledge @felag is also working on something similiar. I've notified him, so you can coordinate things.

**Comment by darkcircle** [comment]
I implemented this feature some days ago, and I was going test for this suggestion code.

**Comment by killing** [comment]
Thanks for the suggestion!
I've seen OpenStack uses similar approach to translate their documentations: https://wiki.openstack.org/wiki/I18n/Tools
But they use DocBook and RST format instead of Markdown. So they don't need to write their own tool to translate to PO and vice versa.
If the markdown to po tool you're working on is reliable enough we'll use it to translate. And I think this tool will be generally interesting for other projects too.

**Comment by darkcircle** [comment]
Yes, 
DocBook supported by gettext which will helps us almost all of automating translation progress.
But, Markdown, as we know, is very easy, simple, efficient format to write any document we write for. I thought that writing tool is more efficient than converting from Markdown to DocBook(and latter is not very stable and doesn't completely proven for production ready).

I consider that my work is just for seafile-docs. because, I did not found many cases(free/open-source software project!) that using gitbook. seafile-docs is very suitable for testing my work. currently, This is not complete, and just for suggestion, as what I said, because there is missing rule to parse some of syntax such as for table(I saw this on the mediawiki, I hesitate whether adding rule is better or not).

You can see a progress and result on my commit 0513a60 and 51b47ee. until now, there does not seem to be a problem, yet.

**Comment by darkcircle** [comment]
i think that enough person seem to see this, so it would better to be closed to prevent merging my pull request, which will be caused to get screwed up master branch
