### ISSUE TITLE
seafile_cli.md is being on one more places.

### ISSUE THREAD

**Issue by darkcircle** [haiwen/seafile-docs#180]
seafile_cli.md contains information about seafile client for CLI.
This file is in
 - client/seafile_cli.md
 - maintain/seafile_cli.md

Its text is about client, so client/seafile_cli.md is should be.
I don't know whether maintain/seafile_cli.md is better to be as is, or not.
There doesn't seems to be a link to maintain/seafile_cli.md anywhere from maintain/
please check this minor issue.
Thanks.

**Comment by freeplant** [comment]
maintain/seafile_cli.md is removed.
