### ISSUE TITLE
too bad

### ISSUE THREAD

**Issue by XakRu** [haiwen/seafile-docs#20]
bad idea to name mysql databases seafile-hub
will be better to name like seafile_hub
to avoid from unreadable characters like seafile@002ddb
because i took error in installation

<pre>
    database:               use exising
    ccnet database:         ccnet-db
    seafile database:       seafile-db
    seahub database:        seahub-db
    database user:          seafile

---------------------------------
Press ENTER to continue, or Ctrl-C to abort
---------------------------------

Generating ccnet configuration ...

done
Successly create configuration dir /var/home/seafile/cloud/haiwen/ccnet.
Generating seafile configuration ...

Done.
done
Generating seahub configuration ...

----------------------------------------
Now creating seahub database tables ...

----------------------------------------
Traceback (most recent call last):
  File "setup-seafile-mysql.py", line 1274, in <module>
    main()
  File "setup-seafile-mysql.py", line 1230, in main
    seahub_config.do_syncdb()
  File "setup-seafile-mysql.py", line 1054, in do_syncdb
    Utils.error('Failed to init seahub database:' % e.args[1])
TypeError: not all arguments converted during string formatting
</pre>

**Comment by shoeper** [comment]
@freeplant close, please
