### ISSUE TITLE
memcached

### ISSUE THREAD

**Issue by ftribrunn** [haiwen/seafile-docs#226]
https://github.com/haiwen/seafile-docs/blob/master/deploy_pro/deploy_in_a_cluster.md#setup-memcached

May I missunderstood the point with memcached.

Do I have to install: "apt-get install memcached"
and config at /etc/memcached.cfg ?

because in the docs its not mentioned. 
only "apt-get install python-memcache"

**Comment by DerDanilo** [comment]
Both as far as I know, this should be updated.

**Comment by shoeper** [comment]
This is already fixed. And can be closed.
