### ISSUE TITLE
Migrate Android and iOS Client changelog

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-docs#354]
Please move https://seacloud.cc/group/3/wiki/android-client-changelog and https://seacloud.cc/group/3/wiki/ios-client-changelog to the manual. It would also be helpful if they could get an update to reflect the most recent changes.

**Comment by shoeper** [comment]
@freeplant

**Comment by freeplant** [comment]
The mobile client changelogs are recorded in the corresponding github repo.

**Comment by shoeper** [comment]
Ok, I'll add links to the releases pages instead.
