### ISSUE TITLE
FileSearch docs outdated?

### ISSUE THREAD

**Issue by egroeper** [haiwen/seafile-docs#374]
According to `/deploy_pro/details_about_file_search.html` and `/deploy_pro/enable_search_and_background_tasks_in_a_cluster.html`Thrift transport (by default on TCP port 9500) is used to contact ElasticSearch and the background node is used as external ES server.

So our config is like this. But looking at the background node I only see connection on port 9200 (default REST port of ElasticSearch) and my ElasticSearch server (bundled with Seafile) doesn't listen on port 9500.
But in my config files port 9500 is still configured. Is this setting ignored nowadays? Am I doing something wrong?

Looking at my elasticsearch process (only java process running on the background node currenttly), it only listens on port 9200 and 11001:

```
sudo lsof -p 6054 | fgrep IP
java    6054 root    5u  IPv4            3154213        0t0     TCP *:11001 (LISTEN)
java    6054 root   86u  IPv6            3151680        0t0     TCP *:9200 (LISTEN)
```

There is no process listening on port 9500:

```
background:~$ sudo netstat -tunpl | fgrep 9500
background:~$ 
```

I only looked at the issue because I'm currently thinking about firewall rules. Only the other seafile nodes should be able to reach the ElasticSearch instance running on the background node (this should be written in the docs like for Memcached!). Currently this is no problem for us, because we are running inside a protected network. But if Seafile is not running in its own protected private network, protection of ES instance is necessary.

According to the docs I only have to open port 9500, where nothing is listening?

**Comment by freeplant** [comment]
The document is updated. Since version 6.1, Seafile uses the default RESTful API port (9200) to communicate with ElasticSearch server.
