### ISSUE TITLE
Wrong username in "Upgrade Seafile Docker Community Edition to 7.0" guide

### ISSUE THREAD

**Issue by konstantingoretzki** [haiwen/seafile-docs#583]
Hi there,

I would like to submit a typo in the official [docs](https://download.seafile.com/published/support/docker/6.3%20upgrade%20to%207.0.md) for upgrading to Docker from Seafile CE 6.3 to 7.0. 
https://download.seafile.com/published/support/docker/6.3%20upgrade%20to%207.0.md

Unfortunately this post is not included in this GitHub repo, so I am just adding this in this issue.

The username under "[Allow seafile remote access](https://download.seafile.com/published/support/docker/6.3%20upgrade%20to%207.0.md#user-content-Allow%20seafile%20remote%20access)" is as far as I know wrong. Looks like some letters got cut off. It's not "seaf", it's "seafile", so it should look like this:

`for database in {ccnet_db,seafile_db,seahub_db}; do sudo docker exec -it seafile /usr/bin/mysql -e "grant all on ${database}.* to 'seafile'@'%.%.%.%' identified by '467fa02f-bf9a-4afb-9300-c4683073162a';"; done`

As I saw it too late it cost me some time to fix this as the seafile user can not connect to the DB anymore. However with the fixed command the login into the DB worked. I guess this should help others so a fix is reasonable.

Best regards,
Konstantin

**Comment by renfeipeng** [comment]
Thank you for your correction, I have fixed it.
