### ISSUE TITLE
Lists Seafile-Client as being GPL; It's actually Apache

### ISSUE THREAD

**Issue by sinni800** [haiwen/seafile-docs#61]
See here:

https://github.com/haiwen/seafile-client/blob/master/LICENSE

Link for historical view later on:

https://github.com/haiwen/seafile-client/commit/c703771bea2366d2cb740c38e020d6a2f207add3#diff-1

Was it ever Apache in the first place? It occurs to me that it is probably hard to switch from a restrictive license like GPL to a less restrictive one to make the pro model legally possible.

**Comment by shoeper** [comment]
Looks like this has been solved.

**Comment by sinni800** [comment]
Yep, I see
