### ISSUE TITLE
FUSE extension Time Stamp is preserved

### ISSUE THREAD

**Issue by Jip-Hop** [haiwen/seafile-docs#64]
In the manual it says the FUSE extension doesn't preserve timestamps. This is no longer the case. Also in the change log it says FUSE implementation has been added in v2.1.0, but there is no mention of FUSE after that version. Clearly somewhere preserving timestamps has been implemented! I actually found a different changelog somewhere online: https://lids.aau.at/display/lids/Seafile. According to this site "Add file timestamp in the FUSE extension" has been added in v4. Could the manual be updated to reflect this? I'm glad time stamps are there! Makes is much easier for me to rsync my libraries to an external harddisk.

**Comment by freeplant** [comment]
Thanks. The document is updated.
