### ISSUE TITLE
Idea: Client docs

### ISSUE THREAD

**Issue by shoeper** [haiwen/seafile-docs#71]
I'd think it could also be useful to create a client manual. There we could get together information for end users and people being interested in Seafile. That book could e.g. be reachable via docs.seafile.com or faq.seafile.com.

**Comment by freeplant** [comment]
A good idea. Thanks. I'll begin work on it in this week.

**Comment by shoeper** [comment]
Although it's hard to find and could include more information. There is something located at https://www.seafile.com/en/help/
